In [1]:
# 1. Carga de bibliotecas
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
# 2. Carga de dados
df = pd.read_csv('https://raw.githubusercontent.com/diogenesjusto/FIAP/master/SHIFT/Data/pib.csv')
df

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi3,PIBi4,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,100.00
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03
2,3,mar/04,110.43,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70
3,4,abr/04,106.77,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,102.05,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,134,fev/15,144.42,147.35,133.73,143.57,147.81,148.96,147.54,157.30,...,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44,148.92
134,135,mar/15,151.68,149.64,163.27,152.09,154.87,179.07,159.56,147.28,...,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44
135,136,abr/15,147.03,153.81,149.93,152.28,161.21,164.74,161.16,162.21,...,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92
136,137,mai/15,148.94,149.66,153.03,149.82,157.03,169.39,158.76,149.06,...,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49
137,138,jun/15,147.37,146.13,147.98,145.84,152.96,162.92,153.86,144.14,...,151.68,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92

In [3]:
# 3. Separação de treino e teste
treino = df.iloc[0:132]
teste = df.iloc[132:138]


# 4. Regressão linear
Y_treino = treino.iloc[:,[2]]

#X = ['BRP']  # Regressão Linear Simples
#X = ['PIBi1', 'PIBi2'] # Modelo Autoregressivo de ordem 2
X = ['PIBi1', 'PIBi2', 'PIBi12'] # Modelo Autoregressivo de ordem 2 + ajuste de caude
X_treino = treino.loc[:,X]

modelo = LinearRegression()
modelo.fit(X_treino, Y_treino)

print(modelo.score(X_treino, Y_treino))
X_teste = teste.loc[:,X]

Y_prev = modelo.predict(X_teste)
Y_real = teste.loc[:,['PIB']]
Erro = Y_prev - Y_real
abs(Erro).mean() # Abs = valor absoluto ou módulo, ou seja, sem sinal. Ou ainda, raiz quadrada do quadrado | Mean = média. Juntando tudo: RMSE

0.9690132512191809

PIB    3.739829
dtype: float64

# Tratamento de valores nulos em Séries Temporais

In [4]:
import numpy as np

In [6]:
# forçar entrada de nulo
df.at[2,'PIB']=np.nan
df.at[3,'PIB']=np.nan
df

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi3,PIBi4,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,100.00
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03
2,3,mar/04,NaN,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70
3,4,abr/04,NaN,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,102.05,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,134,fev/15,144.42,147.35,133.73,143.57,147.81,148.96,147.54,157.30,...,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44,148.92
134,135,mar/15,151.68,149.64,163.27,152.09,154.87,179.07,159.56,147.28,...,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44
135,136,abr/15,147.03,153.81,149.93,152.28,161.21,164.74,161.16,162.21,...,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92
136,137,mai/15,148.94,149.66,153.03,149.82,157.03,169.39,158.76,149.06,...,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49
137,138,jun/15,147.37,146.13,147.98,145.84,152.96,162.92,153.86,144.14,...,151.68,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92

In [7]:
# Preenchimento de valores nulos de uma S.T. com forward fill - isto é, utilizar último valor existente para preencher próximos nulos
df['PIBtff'] = df['PIB'].fillna(method='ffill')

/tmp/ipykernel_6792/824075005.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['PIBtff'] = df['PIB'].fillna(method='ffill')

In [8]:
df

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi4,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12,PIBtff
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,100.00,103.09
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,102.05
2,3,mar/04,NaN,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,102.05
3,4,abr/04,NaN,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,102.05
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,108.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,134,fev/15,144.42,147.35,133.73,143.57,147.81,148.96,147.54,157.30,...,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44,148.92,144.42
134,135,mar/15,151.68,149.64,163.27,152.09,154.87,179.07,159.56,147.28,...,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44,151.68
135,136,abr/15,147.03,153.81,149.93,152.28,161.21,164.74,161.16,162.21,...,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,147.03
136,137,mai/15,148.94,149.66,153.03,149.82,157.03,169.39,158.76,149.06,...,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,148.94
137,138,jun/15,147.37,146.13,147.98,145.84,152.96,162.92,153.86,144.14,...,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,147.37

In [10]:
# Preenchimento de valores nulos a partir de métodos de interpolação
df['PIBtinterpolate'] = df['PIB'].interpolate()

In [11]:
df

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12,PIBtff,PIBtinterpolate
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,102.59,102.24,99.96,101.93,101.17,101.70,100.03,100.00,103.09,103.09
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,102.05,102.05
2,3,mar/04,NaN,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,102.05,104.06
3,4,abr/04,NaN,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,102.05,106.07
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,108.08,108.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,134,fev/15,144.42,147.35,133.73,143.57,147.81,148.96,147.54,157.30,...,154.04,154.75,154.34,148.92,154.49,150.92,151.44,148.92,144.42,144.42
134,135,mar/15,151.68,149.64,163.27,152.09,154.87,179.07,159.56,147.28,...,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44,151.68,151.68
135,136,abr/15,147.03,153.81,149.93,152.28,161.21,164.74,161.16,162.21,...,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,147.03,147.03
136,137,mai/15,148.94,149.66,153.03,149.82,157.03,169.39,158.76,149.06,...,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,148.94,148.94
137,138,jun/15,147.37,146.13,147.98,145.84,152.96,162.92,153.86,144.14,...,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,147.37,147.37

# Criando colunas Lag (isto é, cópia de ua série temporal com "atraso" ou deslocamento de tempo

In [13]:
df[ 'PIBi1_'] = df['PIB'].shift(1)
df

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12,PIBtff,PIBtinterpolate,PIBi1_
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,102.24,99.96,101.93,101.17,101.70,100.03,100.00,103.09,103.09,NaN
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,102.59,102.24,99.96,101.93,101.17,101.70,100.03,102.05,102.05,103.09
2,3,mar/04,NaN,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,104.52,102.59,102.24,99.96,101.93,101.17,101.70,102.05,104.06,102.05
3,4,abr/04,NaN,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,102.05,106.07,NaN
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,108.08,108.08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,134,fev/15,144.42,147.35,133.73,143.57,147.81,148.96,147.54,157.30,...,154.75,154.34,148.92,154.49,150.92,151.44,148.92,144.42,144.42,149.51
134,135,mar/15,151.68,149.64,163.27,152.09,154.87,179.07,159.56,147.28,...,154.04,154.75,154.34,148.92,154.49,150.92,151.44,151.68,151.68,144.42
135,136,abr/15,147.03,153.81,149.93,152.28,161.21,164.74,161.16,162.21,...,156.65,154.04,154.75,154.34,148.92,154.49,150.92,147.03,147.03,151.68
136,137,mai/15,148.94,149.66,153.03,149.82,157.03,169.39,158.76,149.06,...,151.46,156.65,154.04,154.75,154.34,148.92,154.49,148.94,148.94,147.03
137,138,jun/15,147.37,146.13,147.98,145.84,152.96,162.92,153.86,144.14,...,150.70,151.46,156.65,154.04,154.75,154.34,148.92,147.37,147.37,148.94